binary_sensor:

  - id: zone11
    name: Zone 11   
    pin:
      number: $zone11
      mode: INPUT
      inverted: $zone11_inverted
    platform: gpio   
    filters:
      - delayed_on_off: $sensor_debounce_time
    on_state:
      then:
        - light.turn_on: blue_status_led
        - delay: 100ms
        - light.turn_off: blue_status_led
