binary_sensor:

  - id: zone7
    name: Zone 7    
    pin:
      number: $zone7
      mode: INPUT_PULLUP
      inverted: $zone7_inverted
    platform: gpio   
    filters:
      - delayed_on_off: $sensor_debounce_time
    on_state:
      then:
        - light.turn_on: blue_status_led
        - delay: 100ms
        - light.turn_off: blue_status_led
