binary_sensor:

  - id: zone10
    name: Zone 10    
    pin:
      number: $zone10
      mode: INPUT
      inverted: $zone10_inverted
    platform: gpio   
    filters:
      - delayed_on_off: $sensor_debounce_time
    on_state:
      then:
        - light.turn_on: blue_status_led
        - delay: 100ms
        - light.turn_off: blue_status_led
