esphome:
  name: $name
  name_add_mac_suffix: true
  project:
    name: $project_name
    version: $project_version

esp32:  
  board: wesp32
  framework:
    type: arduino
    version: recommended

substitutions:
  status_led_inverted: "false"
  zone1_inverted: "false"
  zone2_inverted: "false"
  zone3_inverted: "false"
  zone4_inverted: "false"
  zone5_inverted: "false"
  zone6_inverted: "false"
  zone7_inverted: "false"
  zone8_inverted: "false"
  zone9_inverted: "false"
  zone10_inverted: "false"
  zone11_inverted: "false"
  zone12_inverted: "false"